name: publish npm package

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Choose package to deploy'
        required: true
        type: choice
        options:
          - compose-controller
          - form-with-dispatch
      version:
        description: 'Choose a strategy for updating the package'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch

permissions:
  contents: write

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Configuring git and npm
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_PUBLISH }}
          git config --global user.name 'vladmilko'
          git config --global user.email 'vladmilko27@gmail.com'
      - name: Installing deps
        run: npm ci
      - name: Upgrading version of ${{ github.event.inputs.package }} 
        run: npm version ${{ github.event.inputs.version }} -w @rhf-bind/${{ github.event.inputs.package }}
      # - name: Tagging new version of ${{ github.event.inputs.package }}
        # run: git tag -a ${{ github.event.inputs.package }}-v${{ npm pkg get version -w @rhf-bind/${{ github.event.inputs.package }} | grep -Eo '\d+\.\d+\.\d+' -m1 }} -m 'Upgrade ${{ github.event.inputs.package }}'
      # - name: Publishing new version of ${{ github.event.inputs.package }}
        # run: npm run publish:${{ github.event.inputs.package }}
      - name: Pushing new version to branch
        run: git commit -am 'Upgrade ${{ github.event.inputs.package }} version' && git push --no-verify
