name: publish npm package

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Choose package to deploy'
        required: true
        type: choice
        options:
          - compose-controller
          - form-with-dispatch
      version:
        description: 'Choose a strategy for updating the package'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_PUBLISH }}
      - run: npm ci
      - run: npm version ${{ github.event.inputs.version }} -w @rhf-bind/${{ github.event.inputs.package }}
      - run: npm run publish:${{ github.event.inputs.package }}
      - run: git add . && git commit -m 'Upgrade ${{ github.event.inputs.package }} version' && git push --no-verify
